package com.collegeerp.Backend.config;

import org.hibernate.engine.jdbc.connections.spi.MultiTenantConnectionProvider;
import org.springframework.stereotype.Component;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.regex.Pattern;

/**
 * Switches PostgreSQL search_path per tenant for every connection Hibernate borrows.
 * Only schema names generated by the tenant provisioning rules are accepted; this keeps
 * the dynamic SET search_path statement defensive even though the value normally comes
 * from a signed JWT.
 */
@Component
public class SchemaMultiTenantConnectionProvider implements MultiTenantConnectionProvider<String> {

    private static final String PUBLIC_SCHEMA = "public";
    private static final Pattern SAFE_SCHEMA = Pattern.compile("[a-z0-9_]{1,63}");

    private final DataSource dataSource;

    public SchemaMultiTenantConnectionProvider(DataSource dataSource) {
        this.dataSource = dataSource;
    }

    @Override
    public Connection getAnyConnection() throws SQLException {
        return dataSource.getConnection();
    }

    @Override
    public void releaseAnyConnection(Connection connection) throws SQLException {
        connection.close();
    }

    @Override
    public Connection getConnection(String tenantIdentifier) throws SQLException {
        String schema = validateSchema(tenantIdentifier);
        Connection connection = getAnyConnection();

        try (var statement = connection.createStatement()) {
            statement.execute("SET search_path TO \"" + schema + "\"");
        } catch (SQLException | RuntimeException ex) {
            try {
                connection.close();
            } catch (SQLException closeException) {
                ex.addSuppressed(closeException);
            }
            throw ex;
        }

        return connection;
    }

    @Override
    public void releaseConnection(String tenantIdentifier, Connection connection) throws SQLException {
        try {
            // Reset the connection before it goes back to the pool so a later request
            // can never inherit another tenant's search_path.
            try (var statement = connection.createStatement()) {
                statement.execute("SET search_path TO \"public\"");
            }
        } finally {
            connection.close();
        }
    }

    private String validateSchema(String tenantIdentifier) {
        if (tenantIdentifier == null || tenantIdentifier.isBlank()) {
            throw new IllegalArgumentException("Tenant schema must not be blank");
        }
        if (!SAFE_SCHEMA.matcher(tenantIdentifier).matches()) {
            throw new IllegalArgumentException("Invalid tenant schema identifier");
        }
        return tenantIdentifier;
    }

    @Override
    public boolean supportsAggressiveRelease() {
        return false;
    }

    @Override
    public boolean isUnwrappableAs(Class<?> unwrapType) {
        return false;
    }

    @Override
    public <T> T unwrap(Class<T> unwrapType) {
        return null;
    }
}
