part of 'main.dart';

class AdminClassSubjectsScreen extends StatefulWidget{final int classId;const AdminClassSubjectsScreen({super.key,required this.classId});@override State<AdminClassSubjectsScreen> createState()=>_AdminClassSubjectsState();}
class _AdminClassSubjectsState extends State<AdminClassSubjectsScreen>{
 List<Map<String,dynamic>> rows=[];List<Map<String,dynamic>> teachers=[];bool loading=true;
 @override void initState(){super.initState();load();}
 Future<void> load()async{try{final r=await Future.wait([ApiService.instance.list('/classes/${widget.classId}/subjects'),ApiService.instance.list('/teachers')]);rows=r[0];teachers=r[1];}catch(e){if(mounted)snack(context,cleanError(e));}finally{if(mounted)setState(()=>loading=false);}}
 Future<void> add()async{final code=TextEditingController(),name=TextEditingController(),credits=TextEditingController(text:'3');int? teacher;String mode='MANDATORY';final ok=await showDialog<bool>(context:context,builder:(c)=>StatefulBuilder(builder:(c,set)=>AlertDialog(title:const Text('Add class subject'),content:SingleChildScrollView(child:Column(children:[TextField(controller:code,decoration:const InputDecoration(labelText:'Subject code')),TextField(controller:name,decoration:const InputDecoration(labelText:'Subject name')),TextField(controller:credits,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Credits')),DropdownButtonFormField<int>(value:teacher,items:teachers.map((t)=>DropdownMenuItem(value:int.tryParse('${t['id']}'),child:Text('${t['firstName']??''} ${t['lastName']??''}'))).toList(),onChanged:(v)=>set(()=>teacher=v),decoration:const InputDecoration(labelText:'Teacher')),DropdownButtonFormField<String>(value:mode,items:const[DropdownMenuItem(value:'MANDATORY',child:Text('Mandatory')),DropdownMenuItem(value:'ELECTIVE',child:Text('Elective'))],onChanged:(v)=>set(()=>mode=v??'MANDATORY'),decoration:const InputDecoration(labelText:'Enrollment'))])),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,code.text.trim().isNotEmpty&&name.text.trim().isNotEmpty&&teacher!=null),child:const Text('Create'))]));if(ok==true){try{await ApiService.instance.mapPost('/classes/${widget.classId}/subjects',{'subjectCode':code.text.trim(),'subjectName':name.text.trim(),'credits':int.parse(credits.text),'teacherId':teacher,'enrollmentMode':mode});if(mounted)snack(context,'Subject added.');load();}catch(e){if(mounted)snack(context,cleanError(e));}}code.dispose();name.dispose();credits.dispose();}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Class Subjects'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),body:loading?const Center(child:CircularProgressIndicator()):ListView.builder(padding:const EdgeInsets.all(16),itemCount:rows.length,itemBuilder:(c,i){final x=rows[i];return Card(child:ListTile(title:Text('${x['subjectName']??x['subjectCode']??'Subject'}',style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('${x['teacherName']??'No teacher'} · ${x['credits']??''} credits · ${x['enrollmentMode']??''}')));}),floatingActionButton:FloatingActionButton.extended(onPressed:add,icon:const Icon(Icons.add),label:const Text('Add subject')));}
