part of 'main.dart';

class AdminTimetableScreen extends StatefulWidget{const AdminTimetableScreen({super.key});@override State<AdminTimetableScreen> createState()=>_AdminTimetableState();}
class _AdminTimetableState extends State<AdminTimetableScreen>{
 List<Map<String,dynamic>> classes=[];List<Map<String,dynamic>> subjects=[];List<Map<String,dynamic>> slots=[];bool loading=true;
 @override void initState(){super.initState();load();}
 Future<void> load()async{try{final raw=await ApiService.instance.request('/classes/mine');classes=raw is List?raw.whereType<Map>().map((x)=>Map<String,dynamic>.from(x)).toList():[];slots=[];}catch(e){if(mounted)snack(context,cleanError(e));}finally{if(mounted)setState(()=>loading=false);}}
 Future<void> selectClass()async{if(classes.isEmpty)return;final selected=await showModalBottomSheet<Map<String,dynamic>>(context:context,builder:(c)=>ListView(shrinkWrap:true,padding:const EdgeInsets.all(16),children:classes.map((x)=>ListTile(title:Text('${x['name']??'Class'}'),subtitle:Text('${x['academicYear']??''} · Sem ${x['semester']??''}'),onTap:()=>Navigator.pop(c,x))).toList()));if(selected==null)return;try{final id=selected['id'];subjects=await ApiService.instance.list('/classes/$id/subjects');if(mounted)setState((){});addSlot(selected);}catch(e){if(mounted)snack(context,cleanError(e));}}
 Future<void> addSlot(Map<String,dynamic> cls)async{if(subjects.isEmpty){snack(context,'Add a subject to this class first.');return;}final subject=subjects.first;final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:Text('Add slot · ${cls['name']}'),content:Text('Selected subject: ${subject['subjectName']??subject['subjectCode']??'Subject'}\n\nUse the web timetable editor for custom day/time slots. The mobile module will be expanded with full slot editing next.'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Close')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Open'))]));if(ok==true&&mounted)snack(context,'Timetable editing is available in the web editor.');}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Timetable Management'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),body:loading?const Center(child:CircularProgressIndicator()):ListView(padding:const EdgeInsets.all(16),children:[const Text('Select a class to inspect its scheduled subjects.',style:TextStyle(fontSize:16)),const SizedBox(height:16),...classes.map((x)=>Card(child:ListTile(title:Text('${x['name']??'Class'}'),subtitle:Text('${x['academicYear']??''} · Semester ${x['semester']??''}'),trailing:const Icon(Icons.chevron_right),onTap:()=>selectClass())))]));
}
