part of 'main.dart';

class AdminMarksScreen extends StatefulWidget{final Map<String,dynamic> schedule;const AdminMarksScreen({super.key,required this.schedule});@override State<AdminMarksScreen> createState()=>_AdminMarksState();}
class _AdminMarksState extends State<AdminMarksScreen>{
 List<Map<String,dynamic>> eligible=[];List<Map<String,dynamic>> marks=[];bool loading=true;
 @override void initState(){super.initState();load();}
 Future<void> load()async{try{final id=widget.schedule['id'];final r=await Future.wait([ApiService.instance.list('/marks/exam-schedule/$id/eligible-students'),ApiService.instance.list('/marks/exam-schedule/$id')]);eligible=r[0];marks=r[1];}catch(e){if(mounted)snack(context,cleanError(e));}finally{if(mounted)setState(()=>loading=false);}}
 Map<String,dynamic>? existing(int sid){for(final x in marks){if('${x['studentId']}'=='$sid')return x;}return null;}
 Future<void> edit(Map<String,dynamic> s)async{final old=existing(int.parse('${s['studentId']}'));final i=TextEditingController(text:'${old?['internalMarks']??''}'),e=TextEditingController(text:'${old?['externalMarks']??''}');final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:Text('${s['studentName']??'Student'}'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:i,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Internal marks')),TextField(controller:e,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'External marks'))]),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Save'))]));if(ok!=true)return;try{final p={'examScheduleId':widget.schedule['id'],'studentId':s['studentId'],'internalMarks':int.tryParse(i.text.trim()),'externalMarks':int.tryParse(e.text.trim())};if(old!=null)await ApiService.instance.mapPut('/marks/${old['id']}',p);else await ApiService.instance.mapPost('/marks',p);if(mounted)snack(context,'Marks saved.');load();}catch(x){if(mounted)snack(context,cleanError(x));}i.dispose();e.dispose();}
 Future<void> publish()async{try{await ApiService.instance.request('/marks/exam-schedule/${widget.schedule['id']}/publish',method:'PUT');if(mounted)snack(context,'Marks published.');load();}catch(e){if(mounted)snack(context,cleanError(e));}}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text('Marks · ${widget.schedule['subjectName']??'Exam'}'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh)),IconButton(onPressed:publish,icon:const Icon(Icons.publish_outlined))]),body:loading?const Center(child:CircularProgressIndicator()):ListView.builder(padding:const EdgeInsets.all(16),itemCount:eligible.length,itemBuilder:(c,i){final s=eligible[i];final m=existing(int.parse('${s['studentId']}'));return Card(child:ListTile(title:Text('${s['studentName']??'Student'}'),subtitle:Text(m==null?'Not graded':'${m['totalMarks']??0}/${m['maxMarks']??widget.schedule['maxMarks']} · ${m['grade']??''} · ${m['status']??''}'),trailing:IconButton(onPressed:()=>edit(s),icon:const Icon(Icons.edit_note)));}));}
}
