part of 'main.dart';

class AdminClassesScreen extends StatefulWidget{const AdminClassesScreen({super.key});@override State<AdminClassesScreen> createState()=>_AdminClassesState();}
class _AdminClassesState extends State<AdminClassesScreen>{
 List<Map<String,dynamic>> rows=[];bool loading=true;
 @override void initState(){super.initState();load();}
 Future<void> load()async{try{final raw=await ApiService.instance.request('/classes/mine');rows=raw is List?raw.whereType<Map>().map((x)=>Map<String,dynamic>.from(x)).toList():[];}catch(e){if(mounted)snack(context,cleanError(e));}finally{if(mounted)setState(()=>loading=false);}}
 Future<void> create()async{final n=TextEditingController(),y=TextEditingController(text:'2026-27'),s=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Create class'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:n,decoration:const InputDecoration(labelText:'Class name')),TextField(controller:y,decoration:const InputDecoration(labelText:'Academic year')),TextField(controller:s,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Semester'))]),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,n.text.trim().isNotEmpty&&s.text.trim().isNotEmpty),child:const Text('Create'))]));if(ok==true){try{await ApiService.instance.mapPost('/classes',{'name':n.text.trim(),'academicYear':y.text.trim(),'semester':int.parse(s.text.trim())});if(mounted)snack(context,'Class created.');load();}catch(e){if(mounted)snack(context,cleanError(e));}}n.dispose();y.dispose();s.dispose();}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Class Management'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),body:loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:load,child:ListView.builder(padding:const EdgeInsets.all(16),itemCount:rows.length,itemBuilder:(c,i){final x=rows[i];return Card(child:ListTile(title:Text('${x['name']??'Class'}',style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('${x['academicYear']??''} · Semester ${x['semester']??''}'),trailing:const Icon(Icons.chevron_right),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>AdminClassDetailScreen(item:x))).then((_)=>load()));})),floatingActionButton:FloatingActionButton.extended(onPressed:create,icon:const Icon(Icons.add),label:const Text('Create class')));}
}
