part of 'main.dart';

class AdminTimetableEditor extends StatefulWidget{final int classId;final String className;final List<Map<String,dynamic>> subjects;const AdminTimetableEditor({super.key,required this.classId,required this.className,required this.subjects});@override State<AdminTimetableEditor> createState()=>_AdminTimetableEditorState();}
class _AdminTimetableEditorState extends State<AdminTimetableEditor>{
 List<Map<String,dynamic>> slots=[];bool loading=true;
 @override void initState(){super.initState();load();}
 Future<void> load()async{try{final all=<Map<String,dynamic>>[];for(final s in widget.subjects){final v=await ApiService.instance.list('/timetable/class-subject/${s['id']}');all.addAll(v);}slots=all;}catch(e){if(mounted)snack(context,cleanError(e));}finally{if(mounted)setState(()=>loading=false);}}
 Future<void> edit([Map<String,dynamic>? old])async{Map<String,dynamic>? result=await showDialog(context:context,builder:(_)=>_SlotDialog(subjects:widget.subjects,old:old));if(result==null)return;try{if(old==null)await ApiService.instance.mapPost('/timetable',result);else await ApiService.instance.mapPut('/timetable/${old['id']}',result);if(mounted)snack(context,old==null?'Slot created.':'Slot updated.');load();}catch(e){if(mounted)snack(context,cleanError(e));}}
 Future<void> remove(Map<String,dynamic> x)async{final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Delete slot?'),content:Text('${x['subjectName']??'Subject'} · ${x['dayOfWeek']??''}'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Delete'))]));if(ok==true)try{await ApiService.instance.request('/timetable/${x['id']}',method:'DELETE');load();}catch(e){if(mounted)snack(context,cleanError(e));}}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(widget.className),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),body:loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.all(16),children:[...slots.map((x)=>Card(child:ListTile(title:Text('${x['subjectName']??'Subject'}'),subtitle:Text('${x['dayOfWeek']??''} · ${x['startTime']??''}–${x['endTime']??''} · ${x['room']??'No room'}'),onTap:()=>edit(x),trailing:IconButton(onPressed:()=>remove(x),icon:const Icon(Icons.delete_outline))))]),const SizedBox(height:12),FilledButton.icon(onPressed:()=>edit(),icon:const Icon(Icons.add),label:const Text('Add timetable slot'))]));}
}
class _SlotDialog extends StatefulWidget{final List<Map<String,dynamic>> subjects;final Map<String,dynamic>? old;const _SlotDialog({required this.subjects,this.old});@override State<_SlotDialog> createState()=>_SlotDialogState();}
class _SlotDialogState extends State<_SlotDialog>{late int subjectId;String day='MONDAY';late TimeOfDay start,end;final room=TextEditingController();
 @override void initState(){super.initState();subjectId=int.tryParse('${widget.old?['classSubjectId']??widget.subjects.first['id']}')??int.parse('${widget.subjects.first['id']}');day='${widget.old?['dayOfWeek']??'MONDAY'}';start=_parse('${widget.old?['startTime']??'09:00'}');end=_parse('${widget.old?['endTime']??'10:00'}');room.text='${widget.old?['room']??''}';}
 TimeOfDay _parse(String s){final p=s.split(':');return TimeOfDay(hour:int.tryParse(p[0])??9,minute:int.tryParse(p[1])??0);}
 String _time(TimeOfDay t)=>'${t.hour.toString().padLeft(2,'0')}:${t.minute.toString().padLeft(2,'0')}:00';
 Future<void> pick(bool isStart)async{final t=await showTimePicker(context:context,initialTime:isStart?start:end);if(t!=null)setState(()=>isStart?start=t:end=t);}
 @override Widget build(BuildContext context)=>AlertDialog(title:Text(widget.old==null?'Add slot':'Edit slot'),content:SingleChildScrollView(child:Column(children:[DropdownButtonFormField<int>(value:subjectId,items:widget.subjects.map((s)=>DropdownMenuItem(value:int.parse('${s['id']}'),child:Text('${s['subjectName']??s['subjectCode']??'Subject'}'))).toList(),onChanged:(v)=>setState(()=>subjectId=v!),decoration:const InputDecoration(labelText:'Subject')),DropdownButtonFormField<String>(value:day,items:const['MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>setState(()=>day=v!),decoration:const InputDecoration(labelText:'Day')),Row(children:[Expanded(child:ListTile(title:Text('Start $start'),onTap:()=>pick(true))),Expanded(child:ListTile(title:Text('End $end'),onTap:()=>pick(false)))]),TextField(controller:room,decoration:const InputDecoration(labelText:'Room'))])),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(context,{'classSubjectId':subjectId,'dayOfWeek':day,'startTime':_time(start),'endTime':_time(end),'room':room.text.trim()}),child:const Text('Save'))]);}
}class AdminTimetableScreen extends StatefulWidget{const AdminTimetableScreen({super.key});@override State<AdminTimetableScreen> createState()=>_AdminTimetableState();}
class _AdminTimetableState extends State<AdminTimetableScreen>{
 List<Map<String,dynamic>> classes=[];bool loading=true;
 @override void initState(){super.initState();load();}
 Future<void> load()async{try{final raw=await ApiService.instance.request('/classes/mine');classes=raw is List?raw.whereType<Map>().map((x)=>Map<String,dynamic>.from(x)).toList():[];}catch(e){if(mounted)snack(context,cleanError(e));}finally{if(mounted)setState(()=>loading=false);}}
 Future<void> openClass(Map<String,dynamic> cls)async{try{final id=cls['id'];final subjects=await ApiService.instance.list('/classes/$id/subjects');if(!mounted)return;Navigator.push(context,MaterialPageRoute(builder:(_)=>AdminTimetableEditor(classId:int.parse('$id'),className:'${cls['name']??'Class'}',subjects:subjects)));}catch(e){if(mounted)snack(context,cleanError(e));}}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Timetable Management'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),body:loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:load,child:ListView.builder(padding:const EdgeInsets.all(16),itemCount:classes.length,itemBuilder:(c,i){final x=classes[i];return Card(child:ListTile(title:Text('${x['name']??'Class'}',style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('${x['academicYear']??''} · Semester ${x['semester']??''}'),trailing:const Icon(Icons.edit_calendar_outlined),onTap:()=>openClass(x)));})));
}
class AdminTimetableEditor extends StatefulWidget{final int classId;final String className;final List<Map<String,dynamic>> subjects;const AdminTimetableEditor({super.key,required this.classId,required this.className,required this.subjects});@override State<AdminTimetableEditor> createState()=>_AdminTimetableEditorState();}
class _AdminTimetableEditorState extends State<AdminTimetableEditor>{
 List<Map<String,dynamic>> slots=[];bool loading=true;
 @override void initState(){super.initState();load();}
 Future<void> load()async{try{final all=<Map<String,dynamic>>[];for(final s in widget.subjects){final v=await ApiService.instance.list('/timetable/class-subject/${s['id']}');all.addAll(v);}slots=all;}catch(e){if(mounted)snack(context,cleanError(e));}finally{if(mounted)setState(()=>loading=false);}}
 Future<void> edit([Map<String,dynamic>? old])async{Map<String,dynamic>? result=await showDialog(context:context,builder:(_)=>_SlotDialog(subjects:widget.subjects,old:old));if(result==null)return;try{if(old==null)await ApiService.instance.mapPost('/timetable',result);else await ApiService.instance.mapPut('/timetable/${old['id']}',result);if(mounted)snack(context,old==null?'Slot created.':'Slot updated.');load();}catch(e){if(mounted)snack(context,cleanError(e));}}
 Future<void> remove(Map<String,dynamic> x)async{final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Delete slot?'),content:Text('${x['subjectName']??'Subject'} · ${x['dayOfWeek']??''}'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Delete'))]));if(ok==true)try{await ApiService.instance.request('/timetable/${x['id']}',method:'DELETE');load();}catch(e){if(mounted)snack(context,cleanError(e));}}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(widget.className),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),body:loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.all(16),children:[...slots.map((x)=>Card(child:ListTile(title:Text('${x['subjectName']??'Subject'}'),subtitle:Text('${x['dayOfWeek']??''} · ${x['startTime']??''}–${x['endTime']??''} · ${x['room']??'No room'}'),onTap:()=>edit(x),trailing:IconButton(onPressed:()=>remove(x),icon:const Icon(Icons.delete_outline))))]),const SizedBox(height:12),FilledButton.icon(onPressed:()=>edit(),icon:const Icon(Icons.add),label:const Text('Add timetable slot'))]));}
}
class _SlotDialog extends StatefulWidget{final List<Map<String,dynamic>> subjects;final Map<String,dynamic>? old;const _SlotDialog({required this.subjects,this.old});@override State<_SlotDialog> createState()=>_SlotDialogState();}
class _SlotDialogState extends State<_SlotDialog>{late int subjectId;String day='MONDAY';late TimeOfDay start,end;final room=TextEditingController();
 @override void initState(){super.initState();subjectId=int.tryParse('${widget.old?['classSubjectId']??widget.subjects.first['id']}')??int.parse('${widget.subjects.first['id']}');day='${widget.old?['dayOfWeek']??'MONDAY'}';start=_parse('${widget.old?['startTime']??'09:00'}');end=_parse('${widget.old?['endTime']??'10:00'}');room.text='${widget.old?['room']??''}';}
 TimeOfDay _parse(String s){final p=s.split(':');return TimeOfDay(hour:int.tryParse(p[0])??9,minute:int.tryParse(p[1])??0);}
 String _time(TimeOfDay t)=>'${t.hour.toString().padLeft(2,'0')}:${t.minute.toString().padLeft(2,'0')}:00';
 Future<void> pick(bool isStart)async{final t=await showTimePicker(context:context,initialTime:isStart?start:end);if(t!=null)setState(()=>isStart?start=t:end=t);}
 @override Widget build(BuildContext context)=>AlertDialog(title:Text(widget.old==null?'Add slot':'Edit slot'),content:SingleChildScrollView(child:Column(children:[DropdownButtonFormField<int>(value:subjectId,items:widget.subjects.map((s)=>DropdownMenuItem(value:int.parse('${s['id']}'),child:Text('${s['subjectName']??s['subjectCode']??'Subject'}'))).toList(),onChanged:(v)=>setState(()=>subjectId=v!),decoration:const InputDecoration(labelText:'Subject')),DropdownButtonFormField<String>(value:day,items:const['MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(v)=>setState(()=>day=v!),decoration:const InputDecoration(labelText:'Day')),Row(children:[Expanded(child:ListTile(title:Text('Start $start'),onTap:()=>pick(true))),Expanded(child:ListTile(title:Text('End $end'),onTap:()=>pick(false)))]),TextField(controller:room,decoration:const InputDecoration(labelText:'Room'))])),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(context,{'classSubjectId':subjectId,'dayOfWeek':day,'startTime':_time(start),'endTime':_time(end),'room':room.text.trim()}),child:const Text('Save'))]);}
}
