part of 'main.dart';

class AdminExamsScreen extends StatefulWidget{const AdminExamsScreen({super.key});@override State<AdminExamsScreen> createState()=>_AdminExamsState();}
class _AdminExamsState extends State<AdminExamsScreen>{
 List<Map<String,dynamic>> exams=[];bool loading=true;
 @override void initState(){super.initState();load();}
 Future<void> load()async{try{exams=await ApiService.instance.list('/exams');}catch(e){if(mounted)snack(context,cleanError(e));}finally{if(mounted)setState(()=>loading=false);}}
 Future<void> create()async{final n=TextEditingController(),type=TextEditingController(text:'END_SEMESTER'),year=TextEditingController(text:'2026-27'),sem=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Create exam'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:n,decoration:const InputDecoration(labelText:'Exam name')),TextField(controller:type,decoration:const InputDecoration(labelText:'Exam type')),TextField(controller:year,decoration:const InputDecoration(labelText:'Academic year')),TextField(controller:sem,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Semester'))]),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,n.text.trim().isNotEmpty&&sem.text.trim().isNotEmpty),child:const Text('Create'))]));if(ok==true){try{await ApiService.instance.mapPost('/exams',{'examName':n.text.trim(),'examType':type.text.trim(),'academicYear':year.text.trim(),'semester':int.parse(sem.text.trim())});if(mounted)snack(context,'Exam created.');load();}catch(e){if(mounted)snack(context,cleanError(e));}}n.dispose();type.dispose();year.dispose();sem.dispose();}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Exam Management'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),floatingActionButton:FloatingActionButton.extended(onPressed:null,icon:const Icon(Icons.add),label:const Text('Schedule')),body:loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:load,child:ListView.builder(padding:const EdgeInsets.all(16),itemCount:exams.length,itemBuilder:(c,i){final x=exams[i];return Card(child:ListTile(title:Text('${x['examName']??'Exam'}',style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('${x['examType']??''} · ${x['academicYear']??''} · Sem ${x['semester']??''}'),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>AdminExamSchedulesScreen(exam:x))));})),floatingActionButton:FloatingActionButton.extended(onPressed:create,icon:const Icon(Icons.add),label:const Text('Create exam')));}
}
class AdminExamSchedulesScreen extends StatefulWidget{final Map<String,dynamic> exam;const AdminExamSchedulesScreen({super.key,required this.exam});@override State<AdminExamSchedulesScreen> createState()=>_AdminSchedulesState();}
class _AdminSchedulesState extends State<AdminExamSchedulesScreen>{List<Map<String,dynamic>> rows=[];bool loading=true;@override void initState(){super.initState();load();}Future<void> load()async{try{rows=await ApiService.instance.list('/exam-schedules/exam/${widget.exam['id']}');}catch(e){if(mounted)snack(context,cleanError(e));}finally{if(mounted)setState(()=>loading=false);}}@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text('${widget.exam['examName']??'Exam'} Schedules'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),body:loading?const Center(child:CircularProgressIndicator()):ListView(padding:const EdgeInsets.all(16),children:rows.map((x)=>Card(child:ListTile(title:Text('${x['subjectName']??'Subject'} · ${x['className']??'Class'}'),subtitle:Text('${x['examDate']??''} · ${x['startTime']??''}-${x['endTime']??''} · ${x['room']??'No room'}'),trailing:Row(mainAxisSize:MainAxisSize.min,children:[Text('${x['maxMarks']??0}'),IconButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>AdminExamScheduleForm(examId:int.parse('${widget.exam['id']}'),old:x))).then((_)=>load()),icon:const Icon(Icons.edit_outlined))]),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>AdminMarksScreen(schedule:x))))).toList()));}
}
