part of 'main.dart';

class AdminExamScheduleForm extends StatefulWidget{final int examId;final Map<String,dynamic>? old;const AdminExamScheduleForm({super.key,required this.examId,this.old});@override State<AdminExamScheduleForm> createState()=>_AdminExamScheduleFormState();}
class _AdminExamScheduleFormState extends State<AdminExamScheduleForm>{
 final cs=TextEditingController(),inv=TextEditingController(),room=TextEditingController(),marks=TextEditingController(text:'100');DateTime date=DateTime.now();TimeOfDay start=const TimeOfDay(hour:9,minute:0),end=const TimeOfDay(hour:10,minute:0);bool saving=false;
 @override void initState(){super.initState();final x=widget.old;if(x!=null){cs.text='${x['classSubjectId']??''}';inv.text='${x['invigilatorId']??''}';room.text='${x['room']??''}';marks.text='${x['maxMarks']??100}';date=DateTime.tryParse('${x['examDate']}')??date;start=_parse('${x['startTime']??'09:00'}');end=_parse('${x['endTime']??'10:00'}');}}
 TimeOfDay _parse(String s){final p=s.split(':');return TimeOfDay(hour:int.tryParse(p[0])??9,minute:int.tryParse(p[1])??0);}
 String _time(TimeOfDay t)=>'${t.hour.toString().padLeft(2,'0')}:${t.minute.toString().padLeft(2,'0')}:00';
 Future<void> save()async{if(cs.text.trim().isEmpty)return;setState(()=>saving=true);final p={'examId':widget.examId,'classSubjectId':int.tryParse(cs.text.trim()),'invigilatorId':int.tryParse(inv.text.trim()),'examDate':'${date.year.toString().padLeft(4,'0')}-${date.month.toString().padLeft(2,'0')}-${date.day.toString().padLeft(2,'0')}','startTime':_time(start),'endTime':_time(end),'room':room.text.trim(),'maxMarks':int.tryParse(marks.text.trim())};try{if(widget.old==null)await ApiService.instance.mapPost('/exam-schedules',p);else await ApiService.instance.mapPut('/exam-schedules/${widget.old!['id']}',p);if(mounted){snack(context,'Exam schedule saved.');Navigator.pop(context,true);}}catch(e){if(mounted)snack(context,cleanError(e));}finally{if(mounted)setState(()=>saving=false);}}
 Future<void> pickDate()async{final d=await showDatePicker(context:context,initialDate:date,firstDate:DateTime(2020),lastDate:DateTime(2100));if(d!=null)setState(()=>date=d);}
 Future<void> pickTime(bool s)async{final t=await showTimePicker(context:context,initialTime:s?start:end);if(t!=null)setState(()=>s?start=t:end=t);}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(widget.old==null?'Schedule Exam':'Edit Schedule')),body:ListView(padding:const EdgeInsets.all(16),children:[TextField(controller:cs,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Class Subject ID')),TextField(controller:inv,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Invigilator User ID (optional)')),ListTile(title:Text('Date: ${date.toLocal().toString().split(' ')[0]}'),trailing:const Icon(Icons.date_range),onTap:pickDate),Row(children:[Expanded(child:ListTile(title:Text('Start: $start'),onTap:()=>pickTime(true))),Expanded(child:ListTile(title:Text('End: $end'),onTap:()=>pickTime(false)))]),TextField(controller:room,decoration:const InputDecoration(labelText:'Room')),TextField(controller:marks,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Maximum marks')),const SizedBox(height:20),FilledButton.icon(onPressed:saving?null:save,icon:const Icon(Icons.save),label:Text(saving?'Saving...':'Save schedule'))]));}
}
