import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { StatusBar } from 'expo-status-bar';
import { NavigationContainer } from '@react-navigation/native';
import { colors, radius, spacing } from './src/theme';
import { getAccessToken, getRole, getUsername, login, logout } from './src/api';
import { AppNavigation } from './src/navigation';

export default function App() {
  const [collegeCode,setCollegeCode]=useState(''); const [username,setUsername]=useState(''); const [password,setPassword]=useState(''); const [role,setRole]=useState<string|null>(null); const [loading,setLoading]=useState(false); const [ready,setReady]=useState(false);
  useEffect(()=>{ Promise.all([getAccessToken(),getRole(),getUsername()]).then(([token,savedRole,name])=>{ if(token){setRole(savedRole); if(name)setUsername(name);} }).finally(()=>setReady(true)); },[]);
  async function handleLogin(){ if(!collegeCode||!username||!password)return Alert.alert('Missing details','Enter college code, username and password.'); try{setLoading(true); const result=await login(collegeCode.trim(),username.trim(),password); setRole(result.role??null);}catch(e){Alert.alert('Login failed',e instanceof Error?e.message:'Please try again.')}finally{setLoading(false)} }
  async function handleLogout(){await logout();setRole(null);setPassword('');}
  if(!ready)return <SafeAreaView style={styles.safe}><ActivityIndicator size="large" color={colors.primary}/></SafeAreaView>;
  if(role!==null)return <NavigationContainer><AppNavigation role={role}/></NavigationContainer>;
  return <SafeAreaView style={styles.safe}><StatusBar style="dark"/><ScrollView contentContainerStyle={styles.container} keyboardShouldPersistTaps="handled"><View style={styles.brandRow}><View style={styles.logo}><Text style={styles.logoText}>E</Text></View><View><Text style={styles.brand}>EduSphere</Text><Text style={styles.subtitle}>College ERP</Text></View></View><View style={styles.hero}><Text style={styles.eyebrow}>MOBILE CAMPUS</Text><Text style={styles.title}>Everything your college needs.</Text><Text style={styles.muted}>One account. The same EduSphere backend. A mobile-first campus experience.</Text></View><View style={styles.card}><Text style={styles.cardTitle}>Sign in</Text><Text style={styles.label}>College code</Text><TextInput value={collegeCode} onChangeText={setCollegeCode} placeholder="College code" placeholderTextColor={colors.muted} style={styles.input} autoCapitalize="characters"/><Text style={styles.label}>Username</Text><TextInput value={username} onChangeText={setUsername} placeholder="Username" placeholderTextColor={colors.muted} style={styles.input} autoCapitalize="none"/><Text style={styles.label}>Password</Text><TextInput value={password} onChangeText={setPassword} placeholder="Password" placeholderTextColor={colors.muted} style={styles.input} secureTextEntry/><Pressable style={styles.button} onPress={handleLogin} disabled={loading}>{loading?<ActivityIndicator color={colors.card}/>:<Text style={styles.buttonText}>Sign in</Text>}</Pressable></View></ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},container:{flexGrow:1,padding:spacing.lg,paddingTop:spacing.xl},brandRow:{flexDirection:'row',alignItems:'center',gap:spacing.sm,marginBottom:spacing.xl},logo:{width:48,height:48,borderRadius:16,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center'},logoText:{color:colors.card,fontSize:26,fontWeight:'800'},brand:{color:colors.text,fontSize:23,fontWeight:'800'},subtitle:{color:colors.muted,fontSize:12},hero:{marginBottom:spacing.lg},eyebrow:{color:colors.primary,fontSize:12,fontWeight:'800',letterSpacing:1.5,marginBottom:spacing.sm},title:{color:colors.text,fontSize:32,lineHeight:39,fontWeight:'800',marginBottom:spacing.sm},muted:{color:colors.muted,fontSize:15,lineHeight:23},card:{backgroundColor:colors.card,borderRadius:radius.card,padding:spacing.lg,shadowColor:colors.text,shadowOpacity:.06,shadowRadius:14,shadowOffset:{width:0,height:3},elevation:2},cardTitle:{color:colors.text,fontSize:21,fontWeight:'800',marginBottom:spacing.lg},label:{color:colors.text,fontSize:13,fontWeight:'700',marginBottom:spacing.xs,marginTop:spacing.sm},input:{height:54,borderWidth:1,borderColor:colors.border,borderRadius:radius.input,paddingHorizontal:spacing.md,color:colors.text,backgroundColor:colors.background},button:{height:54,borderRadius:radius.button,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center',marginTop:spacing.lg},buttonText:{color:colors.card,fontSize:16,fontWeight:'800'}});
