import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, KeyboardAvoidingView, Platform, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { StatusBar } from 'expo-status-bar';
import { NavigationContainer } from '@react-navigation/native';
import { colors, radius, spacing } from './src/theme';
import { getAccessToken, getRole, getUsername, login, logout } from './src/api';
import { AppNavigation } from './src/navigation';

export default function App() {
  const [collegeCode,setCollegeCode]=useState(''); const [username,setUsername]=useState(''); const [password,setPassword]=useState(''); const [role,setRole]=useState<string|null>(null); const [loading,setLoading]=useState(false); const [ready,setReady]=useState(false);
  useEffect(()=>{ Promise.all([getAccessToken(),getRole(),getUsername()]).then(([token,savedRole,name])=>{ if(token){setRole(savedRole); if(name)setUsername(name);} }).finally(()=>setReady(true)); },[]);
  async function handleLogin(){ if(!collegeCode.trim()||!username.trim()||!password)return Alert.alert('Missing details','Enter your college code, username and password.'); try{setLoading(true); const result=await login(collegeCode.trim(),username.trim(),password); setRole(result.role??null);}catch(e){Alert.alert('Login failed',e instanceof Error?e.message:'Please try again.')}finally{setLoading(false)} }
  if(!ready)return <SafeAreaView style={styles.safe}><ActivityIndicator size="large" color={colors.primary}/></SafeAreaView>;
  if(role!==null)return <NavigationContainer><AppNavigation role={role}/></NavigationContainer>;
  return <SafeAreaView style={styles.safe}><StatusBar style="dark"/><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={styles.container} keyboardShouldPersistTaps="handled"><View style={styles.brandRow}><View style={styles.logo}><Text style={styles.logoText}>E</Text></View><View><Text style={styles.brand}>EduSphere</Text><Text style={styles.subtitle}>College ERP</Text></View></View><View style={styles.hero}><View style={styles.badge}><View style={styles.dot}/><Text style={styles.badgeText}>MOBILE CAMPUS</Text></View><Text style={styles.title}>Your campus, beautifully connected.</Text><Text style={styles.muted}>Classes, attendance, assignments and results in one secure mobile workspace.</Text></View><View style={styles.card}><Text style={styles.cardTitle}>Welcome back</Text><Text style={styles.cardHint}>Sign in to continue to your campus.</Text><Text style={styles.label}>College code</Text><TextInput value={collegeCode} onChangeText={setCollegeCode} placeholder="e.g. MREC" placeholderTextColor={colors.muted} style={styles.input} autoCapitalize="characters"/><Text style={styles.label}>Username</Text><TextInput value={username} onChangeText={setUsername} placeholder="Enter username" placeholderTextColor={colors.muted} style={styles.input} autoCapitalize="none"/><Text style={styles.label}>Password</Text><TextInput value={password} onChangeText={setPassword} placeholder="Enter password" placeholderTextColor={colors.muted} style={styles.input} secureTextEntry/><Pressable style={({pressed})=>[styles.button,pressed&&styles.buttonPressed]} onPress={handleLogin} disabled={loading}>{loading?<ActivityIndicator color={colors.card}/>:<Text style={styles.buttonText}>Sign in securely</Text>}</Pressable></View><Text style={styles.footer}>EduSphere ERP · Secure campus access</Text></ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
const styles=StyleSheet.create({flex:{flex:1},safe:{flex:1,backgroundColor:colors.background},container:{flexGrow:1,padding:spacing.lg,paddingTop:spacing.xl,paddingBottom:spacing.lg},brandRow:{flexDirection:'row',alignItems:'center',gap:spacing.sm,marginBottom:spacing.xl},logo:{width:50,height:50,borderRadius:17,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center'},logoText:{color:colors.card,fontSize:27,fontWeight:'900'},brand:{color:colors.text,fontSize:24,fontWeight:'900',letterSpacing:-.4},subtitle:{color:colors.muted,fontSize:12,marginTop:2},hero:{marginBottom:spacing.lg},badge:{alignSelf:'flex-start',flexDirection:'row',alignItems:'center',backgroundColor:colors.lightGreen,borderRadius:radius.pill,paddingHorizontal:11,paddingVertical:7},dot:{width:7,height:7,borderRadius:4,backgroundColor:colors.secondary,marginRight:7},badgeText:{color:colors.primary,fontSize:10,fontWeight:'900',letterSpacing:1.1},title:{color:colors.text,fontSize:31,lineHeight:38,fontWeight:'900',marginTop:spacing.md,marginBottom:spacing.sm},muted:{color:colors.muted,fontSize:15,lineHeight:23},card:{backgroundColor:colors.card,borderRadius:radius.card,padding:spacing.lg,shadowColor:colors.ink,shadowOpacity:.07,shadowRadius:18,shadowOffset:{width:0,height:7},elevation:3},cardTitle:{color:colors.text,fontSize:22,fontWeight:'900'},cardHint:{color:colors.muted,fontSize:13,lineHeight:20,marginTop:4,marginBottom:spacing.md},label:{color:colors.text,fontSize:13,fontWeight:'800',marginBottom:spacing.xs,marginTop:spacing.sm},input:{height:54,borderWidth:1,borderColor:colors.border,borderRadius:radius.input,paddingHorizontal:spacing.md,color:colors.text,backgroundColor:colors.soft,fontSize:15},button:{height:55,borderRadius:radius.button,backgroundColor:colors.primary,alignItems:'center',justifyContent:'center',marginTop:spacing.lg,shadowColor:colors.primary,shadowOpacity:.18,shadowRadius:10,shadowOffset:{width:0,height:5},elevation:2},buttonPressed:{opacity:.86,transform:[{scale:.99}]},buttonText:{color:colors.card,fontSize:16,fontWeight:'900'},footer:{color:colors.muted,fontSize:11,textAlign:'center',marginTop:spacing.lg}});
