import React, { useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { getUsername } from '../api';
import { colors, radius, spacing } from '../theme';

export function AdminDashboardScreen({ navigation }: { navigation: any }) {
  const [name, setName] = useState('Administrator');
  useEffect(() => { getUsername().then((value) => value && setName(value)); }, []);
  const modules = [['Classes','Manage class academic data'],['Attendance','Review attendance operations'],['Assignments','Review coursework'],['Timetable','Manage scheduling'],['Profile','View your account']];
  return <ScrollView style={s.page} contentContainerStyle={s.content}><Text style={s.eyebrow}>ADMIN PORTAL</Text><Text style={s.title}>Welcome, {name}.</Text><Text style={s.muted}>A mobile workspace for day-to-day college administration.</Text><View style={s.hero}><Text style={s.heroLabel}>EDUSPHERE ERP</Text><Text style={s.heroTitle}>Operations at a glance.</Text><Text style={s.heroText}>Use the existing role-protected APIs and tenant context.</Text></View>{modules.map(([title,desc])=><Pressable key={title} style={s.card} onPress={()=>navigation.navigate(title)}><View style={s.icon}><Text style={s.iconText}>{title[0]}</Text></View><View style={s.body}><Text style={s.cardTitle}>{title}</Text><Text style={s.cardText}>{desc}</Text></View><Text style={s.arrow}>›</Text></Pressable>)}</ScrollView>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:colors.background},content:{padding:spacing.lg,paddingTop:spacing.xl,paddingBottom:spacing.xxl},eyebrow:{color:colors.primary,fontSize:12,fontWeight:'800',letterSpacing:1.5},title:{color:colors.text,fontSize:30,fontWeight:'800',marginTop:spacing.sm},muted:{color:colors.muted,fontSize:15,lineHeight:23,marginTop:spacing.sm},hero:{backgroundColor:colors.primary,borderRadius:radius.card,padding:spacing.lg,marginTop:spacing.xl,marginBottom:spacing.md},heroLabel:{color:'#d9f2dc',fontSize:11,fontWeight:'800',letterSpacing:1.2},heroTitle:{color:colors.card,fontSize:24,fontWeight:'800',marginTop:spacing.xs},heroText:{color:'#e8f5e9',fontSize:14,lineHeight:21,marginTop:spacing.xs},card:{backgroundColor:colors.card,borderRadius:radius.card,padding:spacing.md,marginTop:spacing.sm,flexDirection:'row',alignItems:'center',elevation:2},icon:{width:48,height:48,borderRadius:16,backgroundColor:colors.lightGreen,alignItems:'center',justifyContent:'center'},iconText:{color:colors.primary,fontSize:19,fontWeight:'800'},body:{flex:1,marginLeft:spacing.md},cardTitle:{color:colors.text,fontSize:16,fontWeight:'800'},cardText:{color:colors.muted,fontSize:13,marginTop:3},arrow:{color:colors.primary,fontSize:28,marginLeft:spacing.sm}});
